version: '3.8'

services:
  webapi:
    build: ./WebApi
    ports:
      - "5000:80"
    depends_on:
      - db
      - flask
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - backend

  flask:
    build: ./FlaskService
    ports:
      - "5001:5001"
    depends_on:
      - db
    networks:
      - backend

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: map
    volumes:
     - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: diplom2025admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - backend


  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - webapi
    networks:
      - backend

networks:
  backend:
